matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/MyAwesomeProject.xcworkspace
      xcode_scheme: ios/MyAwesomeProject
      script:
        - npm run tsc:ci
        - npm run test:ci
        - npm run docs
        - cd ios
        - zip MyAwesomeProject.zip Users/travis/Library/Developer/Xcode/DerivedData/MyAwesomeProject-ebhqxvazeukrmoedieauaanekckp/Build/Products/Debug-iphonesimulator/MyAwesomeProject.app
        - xcodebuild -scheme MyAwesomeProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - find . -name "*.*"
 