matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      addons:
        sonarcloud:
          organization: "Biswajit Dash"
          token:
            secure: IwveMgIEPRZV7fKnbKt16jARrAtz+HFrRSHIZpJTjH5rJ1z7Q1wkm9ph3A8SUCcomsKUxxiI4s70qtdAnYsQfEMouLvUvO+KzOCB5OrYXq2AyxARmGck4vZuGkReRaI0UGJ6A7NxvKz7ArpdpfgzpuKJsZL3yDDDk2igdqxZjr9X3Mpt1nRKT88yNnQU/5mwoXoKVA3QFMTahZ02FXZ14P2oXtW9MDLg4rOIDjm9vMX+8G/8Wxv5YW6v4PQTdznk76sPVlpQxywnXsf5Qag8r8iy42ZPAII9NJUIUBRv06Kk9qEjf3RaGd+1X/5NU6TUUL3+w0Mq0PAIilKxdOmkTdSdsAj196bFsKoZ2CmQKLTObVluI20LMC3+2yAiw9X+Qt8t2UMlfgn1/roBsRF+YtMJnpfCJk73TD4tjjS8cMxeaMn1T3Se9Dk3oh2XQ1rATIhk7vPrChPbqSISVZGIuIwv44DWs+Uqw5OlntKm7DP6nlVZWrpqhVBzKNxOb7//ARFqBB9ukjdao7yJeynx5lAUGMoUCUsIyqdvdduG7Lojdt2vJYDJ7rOOs9ZR6x8AQW2kTG7Wm6EuKocQYhCUGopExxljDk7aRmwXaJcO/SGVdsclaFCzA447TUDxw2VZdfytyB54ttHqmIk5+hX53d5h45ny4/dAqH/yafyu3gE= 
      sudo: required
      node_js: false
      script:
        - sonar-scanner
    
  