matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/MyAwesomeProject.xcworkspace
      xcode_scheme: ios/MyAwesomeProject
      script:
        - npm run tsc:ci
        - npm run test:ci
        - npm run docs
        - cd ios
        - pwd
        - xcodebuild -scheme MyAwesomeProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - xcodebuild -exportArchive -exportOptionsPlist ../scripts/exportOptions.plist -archivePath MyAwesomeProject.xcarchive -exportPath ./
        - pwd
        - cd /Users/travis/Library/Developer/Xcode/DerivedData/MyAwesomeProject-*/Build/Products/Debug-iphonesimulator
        - zip -r -9 "MyAwesomeProject.app.zip" "MyAwesomeProject.app"
        - curl https://tok_qy99b6dbtmjruqqbpb54gxh1qr@api.appetize.io/v1/apps/vup017aabxtgeky5qx1w93qr44 -F "file=@MyAwesomeProject.app.zip" -F "platform=ios"