matrix:
  include:
  - language: android
    os: linux
    jdk: oraclejdk8
    addons:
      sonarcloud:
        organization: dash-biswajit-github
        token:
          secure: zNVGyv8Ai0/N9u4YE+zsFuqSzQ6YcmKih5qsNPRS3IwX34FiNw7m+OyVFmxgxKaHCENOHMkjGeZRZ0FeB5J4zq6OIgMz7Lv8YqoisXfX5NBqjPrMg+VxOh/MKbGUL7rgIMxQuyIti3aiMaQBKHJPWVJyJ/ykDuIZa/GH6+7sYabVsPE+EEHbrn+CYdgpJ7yj5YcIkNy0vLI8oZt2yA/TgcNEBYyN6ewcophFOZfs4KCziQfCOl79G5KO7X5jjnoIAApcNXEq+OZr6u3CYmbJL5wZKYrlvS1w+vwsnzQUOd7Kd+kzCk1K1NWDWiZSuC2ZwB7UbMVk7yWCy+eKmX2y9HiX8N7s7LszQU3WOly7Qg6YCTe3mwf51neUnUtqKMzvy4rfeD5SSehVvfa0qFcg8U3lbQ4KBFxa85iRztX+8uNN9z6ZquMzVqDgDZD547CCQ1jig45FjmU3HfDDTL+tzm94E0UNQ8ztM4du0bweqt2ZloLC4yVVSWVAnnom7X7DWHzlLCPh8iU2Twy+T/EzKZMGnI6qf/0PWySA2mhXm9xWIrWQ5vMzz+8kkTr+o1ldvrkjEk489zzboC+kpivCIYieSIveGw5hi8V79SaixagDWC4s3CtdU/A6b+62nmzNh/jo7Ugp7Cq/ldqqg21gaVGtpFDPvl+o7cD1ZJBPHC4=
    sudo: required
    node_js: false
    before_install:
    - nvm install 7
    - node --version
    - npm install -g tslint typescript typedoc
    script:
    - sonar-scanner
    
